### ISSUE TITLE
Database downloader is not working

### ISSUE THREAD

**Issue by apcamargo** [geronimp/enrichM#103]
Hi!

The database downloader script is currently not working. I could solve the issue by [altering a single line](https://github.com/geronimp/enrichM/blob/master/enrichm/data.py#L20):

From:
```python
import urllib
```

To:
```python
import urllib.request
```

**Comment by DOieGYuan** [comment]
I came into the same issue, and your solution worked well. Awesome bro!

**Comment by WJunHao** [comment]
Can I download the database from some specific Web pages like "ftp......" without using the "enrichm Data" command?

**Comment by srosales712** [comment]
I have the same problem, but when I  run `import urllib.request` I get an error import: unable to open X server `' @ error/import.c/ImportImageCommand/344.

If I run `enrichm data`
I get error AttributeError: module 'urllib' has no attribute 'request'

Any suggestions.

Thanks,
Stephanie
