### ISSUE TITLE
download the database separately

### ISSUE THREAD

**Issue by liupfskygre** [geronimp/enrichM#117]
Hi, 
   happy 2021!
    I got some issues when downloading the database with enrichm data,
I could download from https://data.ace.uq.edu.au/public/enrichm/ without using enrichm data,

how could i intergerate this db to make enrichm work.

Thanks.

**Comment by wwood** [comment]
You can use e.g.
```
ENRICHM_DB=/path/to/enrichm/data enrichm ...
```
where `/path/to/enrichm/data` contains the downloaded and extracted data.

**Comment by liupfskygre** [comment]
Hi, Ben,
    thanks. got it work.

cheers,
Liu
