### ISSUE TITLE
enrichm data command error

### ISSUE THREAD

**Issue by adityabandla** [geronimp/enrichM#35]
When I run the enrichm data command, I get the following error
IOError: [Errno socket error] [Errno 110] Connection timed out

Any workaround to this?

**Comment by geronimp** [comment]
Hi Aditya,

We had some server maintenance over the weekend which may have disrupted
your connection. Could you try again and let me know if you run into the
same error?

Thanks,


Joel

PhD student, Australian Centre for Ecogenomics (ACE)

**Comment by adityabandla** [comment]
Hi Joel

It works now! Thanks

Regards,
Aditya

**Comment by geronimp** [comment]
Hey Aditya,

Glad to hear it works!

J
