### ISSUE TITLE
Empty TIGRfam Pfam annotations

### ISSUE THREAD

**Issue by adityabandla** [geronimp/enrichM#36]
Hi Joel

I managed to run enrichm annotate on a bunch of genomes (~350 of them). However, the tsv files summarizing the tigrfam and pfam annotations only have zeroes. I can understand that this can be the case for a few genomes, but not for all. These genomes are fairly complete (~70%)

**Comment by geronimp** [comment]
Hi Aditya,

I'm sorry to hear that. Can you send the command you ran and the log file (should be in the output directory) and I'll take a look at your error. If you can, would you also be able to provide a small, reproducible data set that I can work with? Something like a contig should suffice.

Thanks!
J

**Comment by adityabandla** [comment]
Hi Joel

The following is the command I ran
`enrichm annotate --genome_directory ~/genomes --pfam --tigrfam --threads 12 --parallel 4`

Attached is the log
[annotate.log](https://github.com/geronimp/enrichM/files/1959737/annotate.log)

Attached also is a genome file (Gave it a .log extension as Github wont allow me to upload a .fa file)
[Coassembly_metabat_645.fasta.log](https://github.com/geronimp/enrichM/files/1959732/Coassembly_metabat_645.fasta.log)

**Comment by adityabandla** [comment]
I tried updating enrichm to the latest version on Github, but still no luck

**Comment by adityabandla** [comment]
I had a look at the annotate.py code. The issue seemed to be with the parallel command used for the hmmsearch. Since I am using a cluster, I need to invoke parallel using module load. I think without parallel, the hmmsearch step ended without printing an error

TIGRfam annotations seem to work, however Pfam doesn't

**Comment by geronimp** [comment]
Thanks for your patience Aditya,

So if I understand correctly, you found the problem was that the parallel software wasn't in your $PATH, but you're still having trouble with the PFAM annotations?
