### ISSUE TITLE
the --suffix option is not writeable

### ISSUE THREAD

**Issue by TYMichaelsen** [geronimp/enrichM#45]
Hi Joel,
Very simple and easy to use software, nice!

However, when trying to set the --suffix argument it is non-responsive? In  my case the files are .fa and when setting --suffix .fa it prints an error saying no file with suffix .fna was found, irrespective if I use --genome_files or --genome_directory. If this is not a simple bug in the program I will of course start trouble-shooting my own stuff...  

Best,
Thomas

**Comment by geronimp** [comment]
Hi Thomas,

Thanks for your interest in EnrichM. Sorry for the late response I missed this one in my inbox! This has been flagged to me before, so I believe you've identifies a small bug with EnrichM, I'll take a look later tonight to fix the problem. Again, sorry for the delay.

Thanks,
Joel

**Comment by TYMichaelsen** [comment]
No problem, fortunately it is fairly manageable to do a work-around for the moment! :) 
Thomas

**Comment by geronimp** [comment]
This issue should be fixed in the latest version

**Comment by geronimp** [comment]
Thanks for the report!
