### ISSUE TITLE
enrichm data components missing

### ISSUE THREAD

**Issue by TYMichaelsen** [geronimp/enrichM#48]
Hi Joel,
I've installed the latest version of enrichm. The installation worked without issues. Also downloading the the database with `enrichm data` worked without complaints.

However, when running `enrichm annotate` it says:
ko_descriptions.23-08-2018.pickle`
`FileNotFoundError: [Errno 2] No such file or directory: '/home/thomas.michaelsen/databases/enrichm_database_v4/ko_descriptions.23-08-2018.pickle'`

And I've checked the downloaded folders - there is no `ko_descriptions.23-08-2018.pickle`

Best,
Thomas

**Comment by geronimp** [comment]
Hi Thomas,

Thanks for your interest in EnrichM. This is my mistake, ive just uptaded
enrichm but didnt release the new database it needs to run, ill need to
update this in a few days time as i currently have limited access to the
internet.

Sorry about this inconvenience,

Joel

**Comment by geronimp** [comment]
Apologies for the delay. The database has been updated to include the ko descriptions. Please let me know if you run into any other issues after updating the database.
