### ISSUE TITLE
missing ec_to_description.26-11-2018.pickle

### ISSUE THREAD

**Issue by kfiedoruk** [geronimp/enrichM#57]
Hi Joel,
When I'm trying annotate genome using 'enrichm annotate' command I get error: 
FileNotFoundError: [Errno 2] No such file or directory: '/media/kris/HGST/Metabolism/enrichm/database/enrichm_database_v7/ec_to_description.26-11-2018.pickle'. 
I've checked and there is no 'ec_to_description.26-11-2018.pickle' in any enrichm_database_v7 folder. So, could you please advise me how to solve this issue.

Best regards
Chris

**Comment by geronimp** [comment]
Apologies for the delay on this one, I had a few deadlines to meet! The ec_to_description.26-11-2018.pickle is in the latest release of the enrichm database
