### ISSUE TITLE
enrichm explore AttributeError

### ISSUE THREAD

**Issue by TYMichaelsen** [geronimp/enrichM#70]
Hi Joel,

I am running enrichm version 0.4.7 with the database version 2019-03-19-v_8. I have an issue with the explore function, which throws the error 

> AttributeError: 'Namespace' object has no attribute 'enrichment_output'

I am pretty sure the data needed for the explore function are correctly formatted, first I generated annotation and KO matrix :

`enrichm annotate --output annot_test --genome_directory bins --ko`

Then I called the explore function. I provided the --metadata and --queries as specified in the documentation:

`enrichm explore enrichm explore --matrix annot_test/ko_frequency_table.tsv --queries compounds.txt --metadata groups.txt`

This the output in the terminal:

> Traceback (most recent call last):
  File "/space/sharedbin_ubuntu_14_04/software/EnrichM/0.4.7-foss-2018a-Python-3.6.4/bin/enrichm", line 4, in <module>
    __import__('pkg_resources').run_script('enrichm==0.4.7', 'enrichm')
  File "/space/sharedbin_ubuntu_14_04/software/Python/3.6.4-foss-2018a/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/space/sharedbin_ubuntu_14_04/software/Python/3.6.4-foss-2018a/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    exec(code, namespace, namespace)
  File "/space/sharedbin_ubuntu_14_04/software/EnrichM/0.4.7-foss-2018a-Python-3.6.4/lib/python3.6/site-packages/enrichm-0.4.7-py3.6.egg/EGG-INFO/scripts/enrichm", line 359, in <module>
    r.main(args, sys.argv)
  File "/space/sharedbin_ubuntu_14_04/software/EnrichM/0.4.7-foss-2018a-Python-3.6.4/lib/python3.6/site-packages/enrichm-0.4.7-py3.6.egg/enrichm/run.py", line 410, in main
    args.enrichment_output,
AttributeError: 'Namespace' object has no attribute 'enrichment_output'

I am not sure if this is a bug or I am missing some input files? 

I've provided the files used (I just included two bins):
[groups.txt](https://github.com/geronimp/enrichM/files/3152717/groups.txt)
[compounds.txt](https://github.com/geronimp/enrichM/files/3152721/compounds.txt)
[bins.zip](https://github.com/geronimp/enrichM/files/3152722/bins.zip)

Looking forward to your reply.
Best,
Thomas

**Comment by geronimp** [comment]
Hi Thomas,

Sorry you're having trouble. Firstly you may consider updating to the latest version of EnrichM, 0.4.15 and rerunning just to make sure this issue hasn't been fixed already. Otherwise this does look like a bug I'm afraid -all your input files look fine to me. Could you rerun and if it still fails I'll work this issue?

Thanks,

J

**Comment by TYMichaelsen** [comment]
Hi Joel,

Thanks for the quick response. I updated to the latests version and reran the code - now it executes! However, the output folder contains only a log file and nothing else... I'd expect to see some .tsv files similar to the pathway function output.

Best,
Thomas

**Comment by geronimp** [comment]
Thanks Thomas,

Unfortunately this looks a case of code regression due to some additions I needed to make to the `pathway` subcommand. At the moment explore is not functioning, but its now on my to do list for the next release, likely within a week or so. Sorry again about this, I hope to resolve it very soon.

Thanks,
Joel

**Comment by TYMichaelsen** [comment]
Hi Joel,

Ah okay, I look forward to the next release then! :) 

And thanks for the quick response and handling of the issue.

Best,
Thomas

**Comment by geronimp** [comment]
Hi Thomas,

Sorry for the delay on this one, It's part of some pretty major refactoring of enrichM that I wanted to include in the next release, but that has take a little longer than expected. Stay tuned, the fix is on its way soon.

Thanks,
J

**Comment by geronimp** [comment]
Hey Tom, 

enrichm explore is back in enrichm 0.5.0, please let me know if you run into any issues

Thanks,
Joel

**Comment by TYMichaelsen** [comment]
Hi Joel,
Awesome, I will give it a go!

Best,
Thomas
