### ISSUE TITLE
Make --metadata optional in enrichm pathway/explore?

### ISSUE THREAD

**Issue by TYMichaelsen** [geronimp/enrichM#72]
Hi joel, 

I've started a new issue to keep things separated. I've noticed that you've made it mandatory to specify groups of genomes to compare using the `--metadata` option in both the `pathway` and `explore` functions. Would it be possible to skip the comparative analysis and just extract the relevant information for all genomes as "one group"? Or am mistaken how to use the tools?

I'm asking, because this is what I would like to do in many cases - to use the tools exploratively on a set of genomes. Of course it would still be relevant to make comparisons under some circumstances, for which the `--metadata` option are great.

Best,
Thomas

**Comment by geronimp** [comment]
Sure, the work around right now would be to place all genomes in the same group in the file you provide to --metadata but I can certainly add that to the next release also. Keep an eye out for it over the week

**Comment by TYMichaelsen** [comment]
Awesome, and thanks for the temp hack! 
Thomas

**Comment by geronimp** [comment]
Hey Tom, this feature has been added in EnrichM 0.5.0, please let me know if you run into any issues
