### ISSUE TITLE
Missing ko_cutoffs.tsv in the database

### ISSUE THREAD

**Issue by michoug** [geronimp/enrichM#76]
Hi,
I was running the 0.5.0 version of the pipeline with the `--ko_hmm` parameters.
It failed due to a missing `ko_cutoffs.tsv` file in the database (version 10)
Best
Greg

**Comment by geronimp** [comment]
Hi Greg,

Apologies for that - enrichM has changed a bit internally and im still trying to catch up with writing tests for things such as this. I've added an updated version of the enrchm database version 10. Please remove the database you have now and re-install it. Please let me know if you have any trouble.

**Comment by geronimp** [comment]
Hi Greg,

Any luck rerunning with the updated database?

**Comment by michoug** [comment]
Hi Joel
Yes it worked
