### ISSUE TITLE
help page/wiki

### ISSUE THREAD

**Issue by ganiatgithub** [geronimp/enrichM#77]
Hi there,

I cannot look into the information at the help pages/wiki for annotate, classify, etc..

When can that happen?

Cheers

**Comment by geronimp** [comment]
Hey Gani,

I'm looking to release those pages soon - hopefully within a week as I'm wrapping up the paper soon.

Sorry for the inconvenience. In the meantime, is there anything you need to know in particular?

Thanks,

Joel

**Comment by ganiatgithub** [comment]
Hi Joel,

Thank you for the info, now I understand.
I was trouble-shooting, and realize that I need to rename the .fasta files to .fna in order for the program to recognize it. It seems to be running now.

Cheers

**Comment by geronimp** [comment]
Great, I'll close this issue as a duplicate of #17. Thanks again for the bug report

**Comment by abhijeetsingh1704** [comment]
> Hey Gani,
> 
> I'm looking to release those pages soon - hopefully within a week as I'm wrapping up the paper soon.
> 
> Sorry for the inconvenience. In the meantime, is there anything you need to know in particular?
> 
> Thanks,
> 
> Joel

Is there any documentation/Wiki yet?

**Comment by tvtv195** [comment]
Hi Joel, sorry to add this to a thread that's nearly a year old, but it seems we still cannot look into the information at the help pages/wiki for annotate, classify, etc.
