### ISSUE TITLE
--custom_modules not working

### ISSUE THREAD

**Issue by TYMichaelsen** [geronimp/enrichM#78]
Hi Joel, 

Hope your writing is going well!

I wanted to use a custom module in the `enrichm classify` function using the following command:

`enrichm classify --output test --genome_and_annotation_matrix ko_frequency_table.tsv --custom_modules woodcroft_modules.tsv`

But it returns non-sense results. Im not sure about the format of the custom_modules input file, please see the attached files for an example. I have upgraded to the latest (0.5.0) version of enrichm.

Best,
Thomas

[example.zip](https://github.com/geronimp/enrichM/files/3248789/example.zip)

**Comment by geronimp** [comment]
Hi Tom,

Thanks for the report. I'm not sure what the issue is sorry, what do you mean by non-sense results? When I run on the attached data I get genomes annotated with the custom pathway:
```
$ enrichm classify --output test --genome_and_annotation_matrix ko_frequency_table.tsv --custom_modules Woodcroft_modules.tsv  --force
[2019-06-04 05:35:52 AM] INFO: Running command: /home/joel/.local/bin/enrichm classify --output test --genome_and_annotation_matrix ko_frequency_table.tsv --custom_modules Woodcroft_modules.tsv --force
[2019-06-04 05:35:52 AM] INFO: Loading databases
[2019-06-04 05:35:52 AM] INFO: Loading reference db paths
[2019-06-04 05:35:53 AM] INFO: Reading in custom modules: Woodcroft_modules.tsv
[2019-06-04 05:35:54 AM] INFO: Read in annotations for 256 genomes
[2019-06-04 05:35:55 AM] INFO: Writing results to file: test/module_completeness.tsv
[2019-06-04 05:35:55 AM] INFO: Writing results to file: test/module_paths.tsv
[2019-06-04 05:35:55 AM] INFO: Done!
$ grep acetatogenesis test/module_completeness.tsv  | head
SHORT_bin97	acetatogenesis	Custom	2	3	66.67
bin98	acetatogenesis	Custom	1	3	33.33
SHORT_bin104	acetatogenesis	Custom	1	3	33.33
bin135	acetatogenesis	Custom	2	3	66.67
SHORT_bin129	acetatogenesis	Custom	2	3	66.67
SHORT_bin8	acetatogenesis	Custom	2	3	66.67
bin66	acetatogenesis	Custom	2	3	66.67
SHORT_bin58	acetatogenesis	Custom	3	3	100.0
bin151	acetatogenesis	Custom	2	3	66.67
bin7	acetatogenesis	Custom	0	3	0.0
```

And there are only three (space separated) steps in the pathway:
```
acetatogenesis  (K00163,K00627,K00169,K03737,K00174,K00656) (K13788,K04020) (K01512,K00925)
```

Thanks,

Joel

**Comment by TYMichaelsen** [comment]
Hi Joel,

Indeed you are right, it does work - I was presuming that you would ONLY get the modules specified and nothing more, so I did not look deeper into the file... ;) Sorry for the inconvenience.

Anyway, the header of both output files seems corrupted, I get tabs between all characters?

Best,
Thomas

**Comment by michoug** [comment]
> Anyway, the header of both output files seems corrupted, I get tabs between all characters?

I got the same issue
