### ISSUE TITLE
enrichm annotate fasta file error

### ISSUE THREAD

**Issue by TYMichaelsen** [geronimp/enrichM#79]
Hi Joel,

I generated data using enrichm v0.5.0 and the `enrichm annotate` function. The fasta files in the subfolder genome_genes seems to contain only one sequence per file which is copied multiple times throughout the file. The headers are however different. This issue does not occur in the genome_proteins subfolder. 

Best,
Thomas

**Comment by geronimp** [comment]
Hi Tom, Sorry for this bug, I'll look into it for you asap.

**Comment by TYMichaelsen** [comment]
Awesome, looking forward to it!
